--1. Display the number of states present in the LocationTable.
/*SELECT DISTINCT COUNT([State]) AS total_states
from dbo.Location*/
--OR 
SELECT  COUNT(DISTINCT [State]) AS total_states
from dbo.Location
--2. How many products are of regular type?
SELECT COUNT(*) AS Reqular_type
FROM dbo.Product 
WHERE [Type]='Regular'
--OR
SELECT COUNT(DISTINCT Product) AS Reqular_type
FROM dbo.Product 
WHERE [Type]='Regular'

--3. How much spending has been done on marketing of product ID 1?
SELECT SUM(CAST(Marketing AS INT)) AS total_marketing_prod_1
FROM dbo.fact
WHERE ProductId=1
--OR
SELECT SUM(CONVERT(INT,Marketing)) AS total_marketing_prod_1
FROM dbo.fact
WHERE ProductId=1

--4. What is the minimum sales of a product?
SELECT MIN(Sales) AS min_sales_prod
FROM dbo.fact
--5. Display the max Cost of Good Sold (COGS).
SELECT Max(COGS) AS max_COGS
FROM dbo.fact
--6. Display the details of the product where product type is coffee.
SELECT * FROM dbo.Product
WHERE Product_Type='Coffee'

--OR
SELECT * 
FROM dbo.Product AS t1
RIGHT JOIN dbo.fact AS t2 
ON t1.ProductId=t2.ProductId
RIGHT JOIN dbo.[Location]  AS t3
ON t2.Area_Code=t3.Area_Code
WHERE Product_Type='Coffee'

--7. Display the details where total expenses are greater than 40.
SELECT * 
FROM dbo.fact 
WHERE Total_Expenses>40
--8. What is the average sales in area code 719?
SELECT AVG(Sales) Avg_sales_areacode_719
FROM dbo.fact
WHERE Area_Code=719

--9. Find out the total profit generated by Colorado state.
SELECT SUM(CAST(Profit AS INT)) AS total_profit_Colorado
FROM dbo.fact AS f1
JOIN dbo.[Location] AS f2
ON f1.Area_Code=f2.Area_Code
WHERE f2.[State]='Colorado'

--10. Display the average inventory for each product ID.
SELECT AVG(Inventory) Avg_inventory
FROM dbo.fact

--11. Display state in a sequential order in a Location Table.
SELECT [State] 
FROM dbo.[Location]
ORDER BY [State]

--12. Display the average budget of the Product where the average budget margin should be greater than 100.
SELECT Product,AVG(CAST(Budget_Profit AS INT)) AS avg_budget_profit, AVG(Budget_Margin) AS avg_budget_margin
FROM fact f
JOIN Product p
ON f.ProductId=p.ProductId
GROUP BY Product
HAVING AVG(Budget_Margin)>100


--13. What is the total sales done on date 2010-01-01?
SELECT SUM(Sales)
FROM dbo.fact
WHERE [Date]='2010-01-01'

--14. Display the average total expense of each product ID on an individual date.
SELECT [Date],ProductId,AVG(Total_Expenses) AS Avg_totel_expenses
FROM dbo.fact
GROUP BY [Date],ProductId

--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.
SELECT [Date],t2.ProductId,t1.Product_Type,Product,Sales,Profit,[State],t3.Area_Code
FROM dbo.Product AS t1
RIGHT JOIN dbo.fact AS t2 
ON t1.ProductId=t2.ProductId
RIGHT JOIN dbo.[Location]  AS t3
ON t2.Area_Code=t3.Area_Code

--16. Display the rank without any gap to show the sales wise rank.

SELECT ProductId,Sales,DENSE_RANK() OVER(ORDER BY Sales DESC)
FROM fact

--17. Find the state wise profit and sales.

SELECT [State],SUM(CAST(Profit AS INT)),SUM(Sales)
FROM fact f
JOIN [Location] L 
ON f.Area_Code=L.Area_Code
GROUP BY [State]
--18. Find the state wise profit and sales along with the product name.
SELECT [State],SUM(CAST(Profit AS INT)),SUM(Sales),Product
FROM fact f
JOIN [Location] L 
ON f.Area_Code=L.Area_Code
JOIN Product P
ON f.ProductId=P.ProductId
GROUP BY [State],Product
--19. If there is an increase in sales of 5%, calculate the increased sales.
SELECT Sales ,Sales*1.05 AS Increased_Sales
From fact
--20. Find the maximum profit along with the product ID and product_type.
SELECT f.ProductId,Product_Type,MAX(CAST(Profit AS INT)) AS Max_profit
FROM fact f
JOIN Product p
ON f.ProductId=p.ProductId
GROUP BY f.ProductId,Product_Type

--21. Create a stored procedure to fetch the result according to the product type from Product Table. 
CREATE PROCEDURE usp_fetch_sales
(@prod_type nVARCHAR(50))
AS BEGIN

SELECT SUM(Sales) as Total_sales
FROM fact f
JOIN Product p
ON f.ProductId=p.ProductId
WHERE p.Product_Type=@prod_type
GROUP BY p.Product_Type

END
usp_fetch_sales 'Coffee'

--22. Write a query by creating a condition in which if the total expenses is less than
--    60 then it is a profit or else loss.
 SELECT
       CASE WHEN Total_Expenses < 60
	                   THEN 'Profit'
			ELSE 'Loss'
		END AS Profit_or_loss
	FROM fact

--23. Give the total weekly sales value with the date and product ID details.
--    Use roll-up to pull the data in hierarchical order.
 SELECT DATEPART(WEEK,[Date]) As WeekNum,
 ProductId,SUM(Sales) AS total_sale
 FROM fact
 GROUP BY ROLLUP (DATEPART(WEEK,[Date]),ProductId)
 ORDER BY DATEPART(WEEK,[Date]),ProductId
--24. Apply union and intersection operator on the tables which consist of attribute area code.
SELECT Area_Code FROM fact
UNION
SELECT Area_Code FROM [Location]

SELECT Area_Code FROM fact
INTERSECT
SELECT Area_Code FROM [Location]
--25. Create a user-defined function for the product table to fetch a particular product type 
--    based upon the user’s preference.
CREATE FUNCTION udf_fetch_data
(@prod NVARCHAR(50))
RETURNS NVARCHAR(50)
AS BEGIN
   DECLARE @type NVARCHAR(50)

   SELECT @type=Product_Type
   FROM Product
   WHERE Product=@prod

   RETURN @type
END
SELECT dbo.udf_fetch_data ('Amaretto') AS product_type

--SELECT TOP 10 * FROM Product
--26. Change the product type from coffee to tea where product ID is 1 and undo it.
BEGIN TRANSACTION

UPDATE Product
SET Product_Type='Tea'
WHERE ProductId=1

SELECT * FROM Product WHERE ProductId=1

BEGIN TRANSACTION ROLLBACK

SELECT * FROM Product WHERE ProductId=1

--27. Display the date, product ID and sales where total expenses are between 100 to 200.


SELECT [Date],ProductId,Sales,Total_Expenses  
FROM fact
WHERE Total_Expenses Between 100 AND 200
--28. Delete the records in the Product Table for regular type.
DELETE FROM Product WHERE Type='Regular'
--(DOUBT)29. Display the ASCII value of the fifth character from the column Product.
SELECT ASCII(SUBSTRING(Product,5,1)) As fifthcharASCII
FROM Product
